question_category = [
    "1. Computers",
    "2. Sports",
    "3. Science_and_Nature",
    "4. General_Knowledge"
]

question_set = [
    [
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "FLAC stands for 'Free Lossless Audio Condenser';",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Linus Torvalds created Linux and Git.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The logo for Snapchat is a Bell.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "'Windows NT' is a monolithic kernel.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Ada Lovelace is often considered the first computer programmer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The open source program Redis is a relational database server.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
    [
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Peyton Manning retired after winning Super Bowl XLIX.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Skateboarding will be included in the 2020 Summer Olympics in Tokyo.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Tennis was once known as Racquetball.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Olympics tennis court is a giant green screen.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Roger Federer is a famous soccer player.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
    [
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "A person can get sunburned on a cloudy day.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Steel is an alloy of Iron and Carbon.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Shrimp can swim backwards.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Salt is 100% composed of Sodium.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "An atom contains a nucleus.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The chemical element Lithium is named after the country of Lithuania.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "An average human can go two weeks without water.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Psychology is the science of behavior and mind.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ],
    [
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The Great Wall of China is visible from the moon.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Coca-Cola&#039;s original colour was green.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The sum of all the numbers on a roulette wheel is 666.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Nutella is produced by the German company Ferrero.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The French word to travel is &quot;Travail&quot;",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Haggis is traditionally ate on Burns Night.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]
]

def get_questions():
    print("Please select a category from the list below.")
    for ct in question_category:
        print(ct)

    user = input("\nEnter category number(1-4): ")
    try:
        category = int(user) 
        question_data = question_set[category-1]
    except ValueError:
        print("Invalid !! \n>>Please enter Integer only<<")
    except IndexError:
        print("Invalid !! \n>>Please enter number only in the given category range<<")

    cat_num, cat_name = question_category[category-1].split()
    print(f"Your Quiz for '{cat_name}' begins...\n*****ALL THE BEST :)*****\n")
    return question_data
